### ISSUE TITLE
Use FileBrowserPageRoute globally

### ISSUE THREAD

**Issue by JonasWanke** [schul-cloud/schulcloud-flutter#103]
**Is your feature request related to a problem? Please describe.**
The behavior of `FileBrowserPageRoute` is really handy. We should use it throughout the whole app.

**Comment by JonasWanke** [comment]
WIP on branch `issue/103-use-filebrowserpageroute-globally`. Swiping back works, but it interferes with swiping between tabs in `AssignmentDetailScreen`. Current idea:
Provide a customized `HorizontalDragGestureRecognizer` that differs in not accepting swipes to the right when the first tab is open, so the `GestureArena` grants this gesture to our `FancyPageRoute`.

Unfortunately, to implement this behavior, we would have to copy `HorizontalDragGestureRecognizer`, `PanGestureRecognizer` and `DragGestureRecognizer` as the relevant properties are private. And to actually use this new `Recognizer`, we'd also have to copy and slightly adjust a few other classes, as these due to privacy restrictions or tight coupling:
- `TabBarView`
- `_TabBarViewState`
- `PageView`
- `_PageViewState`
- `Scrollable`
- `_ScrollableScope`
- `_ScrollSemantics`
- `_RenderScrollSemantics`

That would result in ca. 1.8k LOC… I really hope we find another way!

(Maybe just use a normal `MaterialPageRoute` on tabbed screens as a workaround?)

**Comment by MarcelGarus** [comment]
I definitely wouldn't want to need to maintain all that code — especially as we would need to stay up-to-date with the Flutter widgets for bug fixes (yes, unfortunately, there are still bugs like https://github.com/flutter/flutter/issues/40580).
Maybe we should just add an `onlySwipeFromEdge` parameter to the route and enable that flag on tabbed screens? That would give us the benefit of having a unified route, so we can customize it globally while circumventing the issue.
