### ISSUE TITLE
Make generic CachedBuilder that already handles error states

### ISSUE THREAD

**Issue by MarcelGarus** [schul-cloud/schulcloud-flutter#118]
All `CachedBuilder`s have
```dart
errorBannerBuilder: (_, error, st) => ErrorBanner(error, st),
errorScreenBuilder: (_, error, st) => ErrorScreen(error, st),
```

We can probably extract that into its own widget.

**Comment by JonasWanke** [comment]
We often repeat the following code or slight variations of it or sometimes just ignore errors:
```dart
if (!update.hasData) {
  return Center(
    child: update.hasError
        ? Text(update.error.toString())
        : CircularProgressIndicator(),
  );
}
```

Maybe we can also provide a Wrapper for `CachedRawBuilder` with attributes that define default loading and error states? E.g.,
- `bool useSliver`
- `bool fullPage`: expand to fill the whole page, show fallback graphic, buttons, etc.
- `bool hideLoading`: just show nothing on loading or error state
  - example: edit overlay inside the submission tab of an assignment—when we don't know the user's permissions, we don't need to show an edit overlay

**Comment by JonasWanke** [comment]
We also need an error page for 404's as soon all detail screens will only get the ID of the entity to display
