### ISSUE TITLE
Add license notice to every file

### ISSUE THREAD

**Issue by MarcelGarus** [schul-cloud/schulcloud-flutter#13]
It is safest to attach the following lines to the start of each source file to most effectively state the exclusion of warranty:

```LICENSE
// Use of this source code is governed by a GPL-style license that can be
// found in the LICENSE file.
```

We can probably include a bot or a Travis test that ensures that's the case in all source files.

**Comment by Th3Ph4nt0m** [comment]
Wouldn't it be better to use the copyright notice that the actual licence suggests?

`Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.`

**Comment by JonasWanke** [comment]
Actually, this is not really necessary. Legally, the LICENSE file in the repository root already applies.
