### ISSUE TITLE
Navigation State

### ISSUE THREAD

**Issue by janrenz** [schul-cloud/schulcloud-flutter#152]
**Describe the bug**
If I enter the homework area via the dashboard (all assignments) the homework icon in the AppNavBar is not selected

**To Reproduce**
1. Go to dashboard
2. Click on All news or all homework

**Expected behavior**
the AppBar Changes to the new are

**Comment by JonasWanke** [comment]
This will be invalidated soon when we move to separate backstacks per tab (#136), similar to other major apps (YouTube, Instagram, StudyPoints) and iOS.
