### ISSUE TITLE
Create framework for displaying persistent banners at the top

### ISSUE THREAD

**Issue by MarcelGarus** [schul-cloud/schulcloud-flutter#172]
**Is your feature request related to a problem? Please describe.**
There are certain conditions where the user should be notified about some persistent condition, for example, if you're logged in with a demo account, you have no internet connection or your token is about to expire or is expired.

**Describe the solution you'd like**
Persistent banners at the top of the screen would be cool.

**Comment by JonasWanke** [comment]
Implemented in #284
