### ISSUE TITLE
Guard against Hive malfunction

### ISSUE THREAD

**Issue by MarcelGarus** [schul-cloud/schulcloud-flutter#213]
Currently, if new types get added on one branch and you swap to another one, the Hive data is corrupted because it doesn't know how to decode type ids. That means that the whole app won't start.
I'm not saying that we shouldn't try to circumvent the Hive DB from getting corrupted, but if it happens, we should fail gracefully by deleting the DB and then continuing with the real app instead of throwing an Exception before `runApp` is called with the correct app.

**Comment by JonasWanke** [comment]
Fixed in #223
