### ISSUE TITLE
How to run the app on IOS

### ISSUE THREAD

**Issue by Juliuspy** [schul-cloud/schulcloud-flutter#349]
Can someone give me instructions how to run the app on IOS  because I dont understand the flutter commands in the wiki

**Comment by ctiedt** [comment]
Have you used Flutter before? Which platform are you using on the PC side? I'm afraid none of our three app developers use iOS devices, so we're not as familiar with Flutter for iOS development. However, we have someone who regularly makes sure that the app runs on iOS, so it should be possible for you to get it running there.

**Comment by Juliuspy** [comment]
I havent used flutter before and dont have an IPhone . Im asking for a friend

**Comment by ctiedt** [comment]
To build the app, you will first need to install Flutter following the instructions on [flutter.dev](https://flutter.dev/docs/get-started/install).
Then, you will have to run the commands listed in the wiki from the command line inside the cloned repository.

However, as far as I know you have to be on macOS using XCode to build Flutter apps for iOS. If you (or your friend) want to try the app without access to a Mac, you can install an Android emulator on your PC instead.

**Comment by Juliuspy** [comment]
thank you very much
