### ISSUE TITLE
Status of the app

### ISSUE THREAD

**Issue by Stupremee** [schul-cloud/schulcloud-flutter#350]
Hey,
we are using the cloud in our school now and I would really like to have an app for it. Do you have any plans or guesses when the app will be published to the App Store (because I don't have a Mac Computer to test it ok my iPhone)?

**Comment by JonasWanke** [comment]
The current plan is to make the app generally available for Android and iOS until summer next year, but we'll see how that plays out.

We'll create [releases on GitHub](https://github.com/hpi-schul-cloud/schulcloud-flutter/releases) (which you can watch) when beta or stable releases are published on the stores. Also, for general questions like this one, we just enabled [GitHub Discussions](https://github.com/hpi-schul-cloud/schulcloud-flutter/discussions).
