### ISSUE TITLE
Add app icon

### ISSUE THREAD

**Issue by MarcelGarus** [schul-cloud/schulcloud-flutter#53]
**Is your feature request related to a problem? Please describe.**
The app has the default Flutter app icon.

**Describe the solution you'd like**
We should use the icon of the Schul-Cloud.

**Comment by MarcelGarus** [comment]
The icon is available here: https://github.com/schul-cloud/schulcloud-client/blob/develop/static/images/logo/app-icon-512.png

**Comment by JonasWanke** [comment]
Fixed in #108
